[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/ipmi",
    "crates/daemon",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/soramikan/pmgfan"

[workspace.dependencies]
pmgfan-core = { path = "crates/core" }
pmgfan-ipmi = { path = "crates/ipmi" }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread", "time"] }
